// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OEBB_Pruefstand.Persistence;

namespace OEBB_Pruefstand.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ÖBB_Prüfstand.Core.Entities.OEBBAntriebseinheit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Leistung")
                        .HasColumnType("int");

                    b.Property<string>("Nummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrueferID")
                        .HasColumnType("int");

                    b.Property<int>("Prüflaufnummer")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Zustand")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PrueferID");

                    b.ToTable("Antriebseinheiten");
                });

            modelBuilder.Entity("ÖBB_Prüfstand.Core.Entities.OEBBAntriebskomponenten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AntriebseinheitsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Baujahr")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Leistung")
                        .HasColumnType("int");

                    b.Property<string>("Nummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AntriebseinheitsID");

                    b.ToTable("Antriebskomponenten");
                });

            modelBuilder.Entity("ÖBB_Prüfstand.Core.Entities.OEBBPruefer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("N_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("V_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pruefer");
                });

            modelBuilder.Entity("ÖBB_Prüfstand.Core.Entities.OEBBAntriebseinheit", b =>
                {
                    b.HasOne("ÖBB_Prüfstand.Core.Entities.OEBBPruefer", "Pruefer")
                        .WithMany()
                        .HasForeignKey("PrueferID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pruefer");
                });

            modelBuilder.Entity("ÖBB_Prüfstand.Core.Entities.OEBBAntriebskomponenten", b =>
                {
                    b.HasOne("ÖBB_Prüfstand.Core.Entities.OEBBAntriebseinheit", "Antriebseinheit")
                        .WithMany()
                        .HasForeignKey("AntriebseinheitsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antriebseinheit");
                });
#pragma warning restore 612, 618
        }
    }
}
